port: 3000
stateFile: persons.json
fixtures:
  - firstname: Jeff
    surname: Stelling
  - firstname: Chris
    surname: Kamara
  - firstname: Alex
    surname: Hammond
  - firstname: Jim
    surname: White
  - firstname: Natalie
    surname: Sawyer
